CREATE TABLE Users (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT (NEWID()),
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    ProfilePictureUrl VARCHAR(255) NOT NULL,
    Role INT NOT NULL DEFAULT 2,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    IsActive BIT NOT NULL DEFAULT 1,
    CONSTRAINT PK_Users PRIMARY KEY (Id)
);

CREATE UNIQUE INDEX IX_Users_Email ON Users (Email);
