CREATE TABLE TournamentFormats (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT (NEWID()),
    Name VARCHAR(50) NOT NULL,
    Description VARCHAR(500) NULL,
    MinTeams INT NOT NULL DEFAULT 2,
    MaxTeams INT NOT NULL DEFAULT 32,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    CONSTRAINT PK_TournamentFormats PRIMARY KEY (Id)
);

CREATE INDEX IX_TournamentFormats_IsActive ON TournamentFormats (IsActive);