CREATE TABLE Teams (
    Id UNIQUEIDENTIFIER NOT NULL DEFAULT (NEWID()),
    Name VARCHAR(200) NOT NULL,
    ShortName VARCHAR(10) NOT NULL,
    LogoUrl VARCHAR(MAX) NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL,
    CONSTRAINT PK_Teams PRIMARY KEY (Id),
    CONSTRAINT FK_Teams_User FOREIGN KEY (UserId) 
        REFERENCES Users (Id)
);

CREATE INDEX IX_Teams_Name ON Teams (Name);
CREATE INDEX IX_Teams_ShortName ON Teams (ShortName);