CREATE TABLE Players (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TeamId UNIQUEIDENTIFIER NOT NULL,
    FirstName NVARCHAR(50) NOT NULL,
    Surname NVARCHAR(50) NOT NULL,
    ProfilePictureUrl NVARCHAR(255) NOT NULL,
    IsCaptain BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    IsActive BIT NOT NULL DEFAULT 1,

    CONSTRAINT FK_Player_Team FOREIGN KEY (TeamId) REFERENCES Teams(Id) ON DELETE CASCADE
);
