CREATE TABLE PlayerStats (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PlayerId UNIQUEIDENTIFIER NOT NULL,
    MatchId UNIQUEIDENTIFIER NOT NULL,
    Goals SMALLINT NOT NULL DEFAULT 0,
    Assists SMALLINT NOT NULL DEFAULT 0,
    YellowCards SMALLINT NOT NULL DEFAULT 0,
    RedCards SMALLINT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    
    CONSTRAINT FK_Player FOREIGN KEY (PlayerId) REFERENCES Players(Id) ON DELETE CASCADE,
    CONSTRAINT FK_Match FOREIGN KEY (MatchId) REFERENCES Matches(Id) ON DELETE NO ACTION,
    CONSTRAINT PlayerPerMatch UNIQUE (PlayerId, MatchId)
);
